// Generated by tools/structure/export_web.py -- do not edit by hand.
// Cache key for everything under /data/. Regenerated whenever the
// simulation data is re-exported, so a stale copy is never served.
export const DATA_VERSION = "20260826T041758Z";
