// Generated by tools/structure/export_web.py, and bumped BY HAND whenever
// anything else under /data/ changes -- see public/data/money-flow/README.md.
// Cache key for everything under /data/, so a stale copy is never served.
export const DATA_VERSION = "20260829T060000Z";
