#!/usr/bin/env python3
"""
Generate a SWIFT-readable cosmological IC with MUSIC.

MUSIC cannot produce a file SWIFT will read without four corrections, three of
which are silent or misleading. They are applied here so nobody has to rediscover
them:

  1. `format = gadget2` writes CLASSIC BINARY. SWIFT reads HDF5 only, and the
     `cleanup_h_factors` flags undo Gadget *unit conventions* inside an HDF5
     file -- they do not make SWIFT read binary. Use `format = arepo`, the only
     MUSIC plugin that emits Gadget-style HDF5.

  2. arepo writes no `PartType1/Masses` dataset for a unigrid run -- the mass
     goes only into `Header/MassTable`. SWIFT declares Masses COMPULSORY
     (gravity/MultiSoftening/gravity_io.h) and never reads MassTable. Aborts.

  3. arepo defaults to kpc and writes no `/Units` group. SWIFT then prints
     "assuming internal unit system" and reads BoxSize=100000 as 1e5 Mpc. This
     one does NOT abort -- it runs happily with the wrong box. Fixed by setting
     arepo_unitlength to Mpc so the file matches the .yml's internal units.

  4. `Header/Flag_Entropy_ICs` is absent; SWIFT reads it unconditionally and
     aborts in io_read_attribute.

Also note MUSIC itself needs a source patch to run on Apple Silicon at all --
see tools/structure/SPEC.md.

Run:  python3 make_ics.py --omega-m 0.30 --sigma8 0.80 --w0 -1.0 --out DIR
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

import h5py
import numpy as np

MUSIC = pathlib.Path(
    "~/Documents/Suttikoon/Research_Projects/MUSIC_Initial_Condition/music/build/MUSIC"
).expanduser()

# Fixed across the whole grid, so that every difference between panels is the
# axis being varied and not something else.
BOX_MPC_H = 100.0
Z_START = 50.0
H0 = 70.3
# Baryon fraction, not baryon density. Holding Omega_b FIXED across the Omega_m
# grid would give f_b = 0.30 / 0.15 / 0.10, and f_b = 0.30 is excluded by BBN and
# the CMB -- it also puts a real baryon feature in the transfer function, which
# is not the effect the Omega_m knob is meant to demonstrate. Fixing f_b instead
# keeps every universe on the grid plausible. 0.151667 is 0.0455/0.30, so the
# fiducial is unchanged.
F_BARYON = 0.0455 / 0.30
NSPEC = 0.961
SEED = 20260825

# SWIFT internal units, from the .yml. These must match or blocker 3 bites.
UNIT_LENGTH_CM = 3.085678e24  # 1 Mpc
UNIT_MASS_G = 1.98841e43  # 1e10 Msun
UNIT_VEL_CMS = 1e5  # 1 km/s

CONF = """# Generated by tools/structure/make_ics.py -- do not edit by hand.
[setup]
boxlength        = {box}
zstart           = {zstart}
levelmin         = {level}
levelmin_TF      = {level}
levelmax         = {level}
baryons          = no
use_2LPT         = yes
use_LLA          = no
periodic_TF      = yes
align_top        = no

[cosmology]
Omega_m          = {omega_m}
Omega_L          = {omega_l}
w0               = {w0}
wa               = 0.0
Omega_b          = {omega_b}
H0               = {h0}
sigma_8          = {sigma8}
nspec            = {nspec}
transfer         = eisenstein

[random]
seed[{level}]          = {seed}

[output]
format           = arepo
filename         = {outfile}
arepo_unitlength = {ulen}
arepo_unitmass   = {umass}
arepo_unitvel    = {uvel}

[poisson]
fft_fine         = yes
accuracy         = 1e-5
pre_smooth       = 3
post_smooth      = 3
smoother         = gs
laplace_order    = 6
grad_order       = 6
"""


def patch_for_swift(path: pathlib.Path) -> None:
    """Apply blockers 2 and 4. Blocker 3 is handled in the config."""
    with h5py.File(path, "r+") as f:
        pt, hdr = f["PartType1"], f["Header"]
        if "Masses" not in pt:
            n = int(np.atleast_1d(hdr.attrs["NumPart_Total"])[1])
            m = float(np.atleast_1d(hdr.attrs["MassTable"])[1])
            if not m > 0:
                raise SystemExit(f"{path.name}: MassTable[1] is {m}; cannot make Masses")
            pt.create_dataset("Masses", data=np.full(n, m, dtype=np.float32))
        if "Flag_Entropy_ICs" not in hdr.attrs:
            hdr.attrs.create("Flag_Entropy_ICs", np.int32(0))


def validate(path: pathlib.Path, a_begin: float) -> None:
    """Fail loudly here rather than silently in a 46-minute run."""
    with h5py.File(path) as f:
        need = {"Coordinates", "Masses", "ParticleIDs", "Velocities"}
        have = set(f["PartType1"].keys())
        if not need <= have:
            raise SystemExit(f"{path.name}: missing {need - have}")
        if "Flag_Entropy_ICs" not in f["Header"].attrs:
            raise SystemExit(f"{path.name}: Flag_Entropy_ICs missing")
        box = float(np.atleast_1d(f["Header"].attrs["BoxSize"])[0])
        if not 1.0 < box < 1e4:
            raise SystemExit(
                f"{path.name}: BoxSize={box}. Expected ~{BOX_MPC_H} (Mpc). "
                "arepo_unitlength is probably wrong -- see blocker 3."
            )
        # SWIFT ignores the IC header's redshift; a_begin in the .yml governs
        # unconditionally. A mismatch runs with wrong initial velocities and no
        # warning, so it is asserted rather than trusted.
        t = float(np.atleast_1d(f["Header"].attrs["Time"])[0])
        if abs(t - a_begin) > 1e-9:
            raise SystemExit(f"{path.name}: IC Time={t} != a_begin={a_begin}")
        n = int(np.atleast_1d(f["Header"].attrs["NumPart_Total"])[1])
        print(f"  validated: {n:,} particles, BoxSize {box} Mpc, a={t:.9f}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--omega-m", type=float, required=True)
    ap.add_argument("--sigma8", type=float, required=True)
    ap.add_argument("--w0", type=float, default=-1.0)
    ap.add_argument("--level", type=int, default=7, help="7 = 128^3, 6 = 64^3")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    # The caller owns the tag. run_grid.sh formats sigma_8 to three decimals so
    # that the two amplitude conventions produce distinct directory names, and a
    # tag computed independently here drifted from it -- MUSIC wrote
    # ic_..._s0.80_... while the generated run.yml asked for ic_..._s0.800_...,
    # and SWIFT died in H5Fopen with no useful message.
    ap.add_argument("--tag", help="directory/file tag; derived if omitted")
    a = ap.parse_args()

    a.out.mkdir(parents=True, exist_ok=True)
    tag = a.tag or f"Om{a.omega_m:.2f}_s{a.sigma8:.3f}_w{a.w0:+.1f}"
    outfile = f"ic_{tag}.hdf5"
    conf = a.out / f"{tag}.conf"
    conf.write_text(
        CONF.format(
            box=BOX_MPC_H, zstart=Z_START, level=a.level,
            omega_m=a.omega_m, omega_l=1.0 - a.omega_m, w0=a.w0,
            omega_b=round(F_BARYON * a.omega_m, 6), h0=H0, sigma8=a.sigma8, nspec=NSPEC, seed=SEED,
            outfile=outfile, ulen=UNIT_LENGTH_CM, umass=UNIT_MASS_G, uvel=UNIT_VEL_CMS,
        )
    )

    print(f"  {tag}: running MUSIC ...")
    r = subprocess.run([str(MUSIC), conf.name], cwd=a.out, capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout[-3000:] + r.stderr[-3000:])
        raise SystemExit(f"MUSIC failed ({r.returncode})")

    path = a.out / outfile
    patch_for_swift(path)
    validate(path, 1.0 / (1.0 + Z_START))
    print(f"  wrote {path.name}  ({path.stat().st_size / 2**20:.0f} MB)")


if __name__ == "__main__":
    main()
