#!/usr/bin/env python3
"""
The scenario behind /software/where-did-my-money-go/.

Built from a real ledger rather than invented, because the thing that makes a
money demo convincing is not the numbers -- it is the RHYTHM. Rent lands on the
same day every month and dwarfs everything else. Food is two thirds of the rows
and almost none of the money. Savings transfers cluster in the last week, after
payday. Nobody makes that shape up correctly, and a hand-written ledger reads
like a hand-written ledger the moment you look at the daily counts.

So this reads the author's own SQLite ledger and keeps the shape while
discarding the content. What actually does the protecting is the merging, the
clipping and the fact that the source ordering is not published -- the jitter
alone would not, since the seed below is a constant in a file the site links
to. It is the author's own ledger and that trade is deliberate:

  * only the two most recent full months are used
  * every free-text note and description is DROPPED -- that is where a person
    actually shows through, far more than any amount does
  * amounts are re-denominated to pounds and then jittered +/- 18 per cent
  * dates move +/- 2 days within their month, so the fixed bills stay a cluster
    without staying a fingerprint
  * per-category outliers are clipped at the 90th percentile: a single huge row
    is both identifying and ruinous for the y-scale
  * categories with fewer than MIN_CAT_ROWS rows fold into Other
  * same-day, same-subcategory rows are merged, which is also how the app's own
    hold-to-read readout groups repeats
  * rows are shuffled within each day

The seed is fixed, so the file is reproducible and a rebuild produces no diff.

Writes one file: public/data/money-flow/seed.json, which the web demo fetches.
The phone app was seeded with the same rows for the screenshots on that page,
but through the app's own restore path rather than from here.

Run:  python3 tools/build_money_seed.py

NOTE: when seed.json changes, bump DATA_VERSION in
src/scripts/explore/data-version.js by hand. It is the cache key for everything
under /data/, and it is otherwise only regenerated by the simulation export, so
a returning reader would keep the old ledger indefinitely.
"""

from __future__ import annotations

import collections
import datetime as dt
import json
import pathlib
import random
import sqlite3

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "public/data/money-flow"
LEDGER = pathlib.Path(
    "~/Documents/Suttikoon/Fun_Projects/money_tracker/data/raw/ledger.db"
).expanduser()

#: Two most recent full months in the source ledger.
WINDOW = ("2026-06-01", "2026-08-01")

#: Months to shift the finished scenario forward by, and the last day to keep.
#:
#: The source window is the last two COMPLETE months of the ledger, which is
#: what makes it dense. Shipped unshifted, though, it sits a month in the past,
#: and the app's own screens are built around the period you are in: Budget's
#: "this period" panel and the Transactions month both open on today and cannot
#: be pointed elsewhere without clicking. Screenshots of the real app therefore
#: came out empty. Shifted forward one month and cut at the day the scenario is
#: generated, every screen opens with something on it, and the second month is
#: part-finished -- which is what a real month looks like when you look at it.
SHIFT_MONTHS = 1
CUTOFF = "2026-08-28"

#: Deterministic, so a rebuild is a no-op in git.
SEED = 20260828

#: Direction lives in the type, never in the sign of the amount. Same map the
#: app uses; the demo module has a copy and the two must agree.
SIGN = {
    "Income": 1,
    "Expense": -1,
    "Transfer-In": 1,
    "Transfer-Out": -1,
    "Saving": -1,
    "Adjustment-In": 1,
    "Adjustment-Out": -1,
}

#: Real account names -> the app's own defaults. Dime is a brokerage and Next
#: Savings a savings account; both are folded into one Savings account, which
#: keeps the demo to five accounts and makes the savings story legible. A
#: transfer whose two legs land on the same account after this is dropped.
ACCOUNTS = {
    "Bank Accounts": "Bank Accounts",
    "Credit Card": "Credit Card",
    "Cash": "Cash",
    "G Wallet": "Wallet",
    "Next Savings": "Savings",
    "Dime": "Savings",
}
SAVINGS_ACCOUNTS = ["Savings"]

#: The salary is the anchor: everything is scaled so a month's pay lands here,
#: which keeps rent, food and savings at their true FRACTIONS of income while
#: making the absolute figures somebody else's.
TARGET_SALARY_GBP = 2180.0

#: Rent, flat every month. See the note beside the salary in main().
RENT_GBP = 506.50

AMOUNT_JITTER = (0.82, 1.18)
DATE_JITTER = 2
CLIP_PERCENTILE = 90
MIN_CAT_ROWS = 4

#: Spelling fixes carried over from the source ledger, which was typed on a
#: phone over a year. Harmless there; on a public page they read as sloppiness
#: about the app rather than about the typing.
SPELLING = {
    "Eletronics": "Electronics",
    "Maintainance": "Maintenance",
}

#: The app's own 50/30/20 assignment.
NEEDS = ["Bills", "Food", "Household", "Health", "Transport", "Car", "Family", "Education"]
WANTS = ["Social Life", "Travel", "Beauty", "Apparel", "Gift", "Subscription", "Other"]


def day(period: str) -> dt.date:
    """The ledger stores 'YYYY-MM-DD 00:00:00'."""
    return dt.date.fromisoformat(period[:10])


def percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    k = (len(s) - 1) * pct / 100.0
    lo, hi = int(k), min(int(k) + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


def round_money(x: float) -> float:
    """Nearest 5p under twenty pounds, nearest 50p above.

    Real small purchases have pence and real large ones tend not to; rounding
    everything to the same grid is one of the things that makes generated data
    look generated.
    """
    if abs(x) < 20:
        return round(round(x * 20) / 20, 2)
    return round(round(x * 2) / 2, 2)


def main() -> None:
    def shift_month(iso: str) -> str:
        """Move a date SHIFT_MONTHS forward, clamped to the target month's length."""
        import calendar

        y, m, d = (int(x) for x in iso.split("-"))
        m += SHIFT_MONTHS
        y += (m - 1) // 12
        m = (m - 1) % 12 + 1
        return f"{y:04d}-{m:02d}-{min(d, calendar.monthrange(y, m)[1]):02d}"

    rng = random.Random(SEED)
    con = sqlite3.connect(f"file:{LEDGER}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row

    rows = [dict(r) for r in con.execute("SELECT * FROM transactions ORDER BY period, id")]
    con.close()

    start, end = WINDOW
    scale = TARGET_SALARY_GBP / 40000.0

    # ---------------------------------------------------------- openings --
    # The balance each account carried INTO the window, from the whole history
    # before it. Without this the chart would start at zero and the first month
    # would be a fiction.
    opening: dict[str, float] = collections.defaultdict(float)
    for r in rows:
        if r["period"][:10] >= start:
            continue
        acct = ACCOUNTS.get(r["account"])
        s = SIGN.get(r["txn_type"])
        if acct and s:
            opening[acct] += s * r["amount"]

    window = [r for r in rows if start <= r["period"][:10] < end]

    # ------------------------------------------------------- clip + fold --
    # Per-category caps, computed on the window before anything is scaled.
    by_cat: dict[str, list[float]] = collections.defaultdict(list)
    for r in window:
        if r["txn_type"] == "Expense":
            by_cat[r["category"]].append(r["amount"])
    caps = {c: percentile(v, CLIP_PERCENTILE) for c, v in by_cat.items()}
    rare = {c for c, v in by_cat.items() if len(v) < MIN_CAT_ROWS}

    # ---------------------------------------------------------- transfers --
    # Pairs, not legs. A transfer is two rows that have to move, scale and
    # merge together or the balance tells a lie on one side of it. They are
    # pulled out here, merged by (day, from, to) -- four separate top-ups into
    # savings on payday are one decision, and drawing them as four bars is
    # noise -- and re-emitted as legs at the end with fresh ids.
    legs: dict[str, list[dict]] = collections.defaultdict(list)
    for r in window:
        if r["txn_type"] in ("Transfer-In", "Transfer-Out") and r["transfer_id"]:
            legs[r["transfer_id"]].append(r)

    pairs: dict[tuple, dict] = {}
    for tid, pair in legs.items():
        if len(pair) != 2:
            continue
        src = next((x for x in pair if x["txn_type"] == "Transfer-Out"), None)
        dst = next((x for x in pair if x["txn_type"] == "Transfer-In"), None)
        if src is None or dst is None:
            continue
        a, b = ACCOUNTS.get(src["account"]), ACCOUNTS.get(dst["account"])
        # Next Savings <-> Dime both became Savings: a transfer to itself.
        if a is None or b is None or a == b:
            continue
        d = day(src["period"])
        shift = random.Random(f"{SEED}-{tid}").randint(-DATE_JITTER, DATE_JITTER)
        moved = d + dt.timedelta(days=shift)
        if moved.month != d.month:
            moved = d
        j = random.Random(f"{SEED}amt-{tid}").uniform(*AMOUNT_JITTER)
        # Merged by MONTH, not by day. Paying a card down in four instalments
        # across a fortnight is one bill, and the source ledger has 37 distinct
        # day/pair combinations over two months -- more transfer bars than
        # there are days. Monthly, it is eight, and each one is a decision the
        # reader can actually see. The pair lands on the last day it occurred,
        # which for both the card and the savings top-up is just after payday.
        # Orient savings movements as deposits. The source records both
        # directions and the monthly merge nets them, which on this window came
        # out pointing OUT of savings -- the exact opposite of the thing the
        # page is built to show, which is that moving money into savings drops
        # an account balance and leaves net worth untouched.
        if b in SAVINGS_ACCOUNTS or a in SAVINGS_ACCOUNTS:
            if a in SAVINGS_ACCOUNTS:
                a, b = b, a
        key = (moved.strftime("%Y-%m"), a, b)
        amt = src["amount"] * scale * j
        if key in pairs:
            pairs[key]["amount"] += amt
            if moved.isoformat() > pairs[key]["period"]:
                pairs[key]["period"] = moved.isoformat()
        else:
            pairs[key] = {"period": moved.isoformat(), "from": a, "to": b, "amount": amt}

    # ------------------------------------------------------------ shaping --
    shaped: list[dict] = []
    for r in window:
        acct = ACCOUNTS.get(r["account"])
        if acct is None or r["txn_type"] not in SIGN:
            continue
        if r["txn_type"] in ("Transfer-In", "Transfer-Out"):
            continue

        cat = r["category"] or "Other"
        sub = SPELLING.get(r["subcategory"], r["subcategory"]) or ""
        amount = r["amount"]

        if r["txn_type"] == "Expense":
            amount = min(amount, caps.get(cat, amount))
            if cat in rare:
                cat, sub = "Other", ""

        d = day(r["period"])
        # Jitter the date, but never out of its own month: the month bands and
        # the "rent lands at the start" shape both depend on that.
        shift = rng.randint(-DATE_JITTER, DATE_JITTER)
        moved = d + dt.timedelta(days=shift)
        if moved.month != d.month:
            moved = d

        j = rng.uniform(*AMOUNT_JITTER)
        # Everything is jittered except the salary. A salary is the one figure
        # in a ledger that does NOT move, and jittering it swung pay by 29 per
        # cent between the two months -- which then showed up in the budget
        # strip as a catastrophic month, for a reason that was an artefact of
        # this script rather than anything in the data. It is set flat to the
        # anchor instead, and everything else is scaled around it.
        # Rent is flat-pinned for the same reason as the salary below it: it is
        # a standing order, and jittering it moved it 21 per cent between two
        # months that sit side by side in the ledger. The value is the median of
        # the source's own rent rows, scaled.
        if r["txn_type"] == "Expense" and sub == "Rent":
            shaped.append(
                {
                    "period": moved.isoformat(),
                    "account": acct,
                    "type": "Expense",
                    "category": "Bills",
                    "subcategory": "Rent",
                    "amount": RENT_GBP,
                }
            )
            continue

        if r["txn_type"] == "Income" and cat == "Salary":
            shaped.append(
                {
                    "period": moved.isoformat(),
                    "account": acct,
                    "type": "Income",
                    "category": "Salary",
                    "subcategory": "",
                    "amount": TARGET_SALARY_GBP,
                }
            )
            continue

        shaped.append(
            {
                "period": moved.isoformat(),
                "account": acct,
                "type": r["txn_type"],
                "category": cat,
                "subcategory": sub,
                "amount": amount * scale * j,
            }
        )

    # -------------------------------------------------------------- merge --
    # Same day, same account, same type, same CATEGORY -> one row. Three
    # coffees and a sandwich on a Tuesday become one Food bar, which is what
    # the app's own hold-to-read readout does when it groups repeats. The key
    # deliberately ignores subcategory: keying on it left 315 expense rows over
    # two months, six bars a day, and at ten pixels a day on a phone that is a
    # grey smear rather than a chart. The surviving row keeps the subcategory
    # of its largest contributor, so the ledger still says Rent rather than
    # Bills.
    merged: dict[tuple, dict] = {}
    order: list[tuple] = []
    for r in shaped:
        # Rent keeps its own row rather than merging into Bills. It is the one
        # expense the page names a figure for, and folding it in with whatever
        # else the standing orders did that morning made it £506.50 one month
        # and £546.00 the next -- which reads as a jittered rent rather than as
        # a merged row, and contradicts the flat pin above.
        key = (r["period"], r["account"], r["type"], r["category"], r["subcategory"] == "Rent")
        if key in merged:
            m = merged[key]
            if r["amount"] > m["_top"]:
                m["_top"] = r["amount"]
                m["subcategory"] = r["subcategory"]
            m["amount"] += r["amount"]
        else:
            m = dict(r)
            m["_top"] = r["amount"]
            merged[key] = m
            order.append(key)

    out_rows = [merged[k] for k in order]
    for r in out_rows:
        r["amount"] = round_money(r["amount"])
        del r["_top"]
    out_rows = [r for r in out_rows if r["amount"] > 0]

    # NOTE ON ORDER: the shift and the cutoff are applied to `out_rows` before
    # the savings cap is computed, because the cap is meant to equal the residual
    # the budget strip shows and the strip only ever sees post-cutoff rows.
    # Computed before, August capped against £445.70 of a full source month while
    # the strip showed £510.95, and the comment below claimed an agreement that
    # did not exist.
    for r in out_rows:
        r["period"] = shift_month(r["period"])
    out_rows = [r for r in out_rows if r["period"] <= CUTOFF]

    # A month cannot save more than it had left. Merging the source's frequent
    # savings top-ups into one monthly lump produced deposits of about 85 per
    # cent of pay, in months whose needs alone were 60 per cent -- arithmetic
    # that only balanced because the opening float absorbed it, and which reads
    # as nonsense next to the budget strip. Each savings deposit is capped at
    # what that month actually had spare, which is the same residual the strip
    # shows. The two now agree, and that agreement is worth pointing at in the
    # prose.
    month_in: dict[str, float] = collections.defaultdict(float)
    month_out: dict[str, float] = collections.defaultdict(float)
    for r in out_rows:
        m = r["period"][:7]
        if r["type"] == "Income":
            month_in[m] += r["amount"]
        elif r["type"] == "Expense":
            month_out[m] += r["amount"]
    # Shift the pairs too, and drop any that fall past the cutoff.
    for pr in pairs.values():
        pr["period"] = shift_month(pr["period"])
    for key in [k for k, pr in pairs.items() if pr["period"] > CUTOFF]:
        del pairs[key]

    # One cap per month, not per pair: two savings pairs in the same month would
    # otherwise each be allowed the whole residual and could jointly exceed it.
    spare_left: dict[str, float] = {}
    for pr in sorted(pairs.values(), key=lambda x: x["period"]):
        if pr["to"] not in SAVINGS_ACCOUNTS:
            continue
        m = pr["period"][:7]
        if m not in spare_left:
            spare_left[m] = max(0.0, month_in[m] - month_out[m])
        take = min(pr["amount"], spare_left[m])
        pr["amount"] = take
        spare_left[m] -= take

    # Transfer legs, from the merged pairs above.
    for pr in pairs.values():
        amt = round_money(pr["amount"])
        if amt <= 0:
            continue
        tid = f"t{len(out_rows)}"
        for acct, kind in ((pr["from"], "Transfer-Out"), (pr["to"], "Transfer-In")):
            out_rows.append(
                {
                    "period": pr["period"],
                    "account": acct,
                    "type": kind,
                    "category": pr["to"] if kind == "Transfer-Out" else pr["from"],
                    "subcategory": "",
                    "amount": amt,
                    "transferId": tid,
                }
            )

    # Shuffle within each day, then number. The id is what breaks ties in the
    # waterfall's sort, so it has to exist and it has to be stable.
    buckets: dict[str, list[dict]] = collections.defaultdict(list)
    for r in out_rows:
        buckets[r["period"]].append(r)
    final: list[dict] = []
    for period in sorted(buckets):
        chunk = buckets[period]
        rng.shuffle(chunk)
        # Money in before money out, within a day.
        #
        # The order of rows sharing a date is otherwise arbitrary, and the
        # waterfall draws them in it -- so on payday, with the salary shuffled
        # behind the savings transfer, the account dipped to minus a hundred
        # and fifty pounds and came straight back. Nothing like that happened;
        # it is the shuffle showing through. Inflows first is also the honest
        # order: the salary lands in the morning and the standing orders go out
        # after it.
        chunk.sort(key=lambda r: 0 if SIGN[r["type"]] > 0 else 1)
        final.extend(chunk)
    for i, r in enumerate(final, start=1):
        r["id"] = i
        if not r.get("transferId"):
            r.pop("transferId", None)
        if not r.get("subcategory"):
            r.pop("subcategory", None)

    final.sort(key=lambda r: (r["period"], r["id"]))
    for i, r in enumerate(final, start=1):
        r["id"] = i

    # ------------------------------------------------------- categories --
    cats: dict[str, dict[str, list[str]]] = {"Expense": {}, "Income": {}}
    for r in final:
        if r["type"] not in ("Expense", "Income"):
            continue
        bag = cats[r["type"]].setdefault(r["category"], [])
        sub = r.get("subcategory")
        if sub and sub not in bag:
            bag.append(sub)
    for kind in cats:
        for c in cats[kind]:
            cats[kind][c].sort()

    # ---------------------------------------------------------- openings --
    # The computed carry-in leaves two asset accounts slightly negative, which
    # is an artefact of a source ledger whose first months are sparse rather
    # than anything that happened. Lift each asset account just enough that its
    # running balance never goes below zero across the window; a Credit Card is
    # a liability and is left alone, because a negative balance there is the
    # whole point of it.
    for name in ["Bank Accounts", "Cash", "Wallet", "Savings"]:
        run = opening.get(name, 0.0) * scale
        low = run
        for r in final:
            if r["account"] == name:
                run += SIGN[r["type"]] * r["amount"]
                low = min(low, run)
        if low < 0:
            opening[name] = (opening.get(name, 0.0) * scale - low + 25.0) / scale

    # Net worth crossing zero is a distraction rather than a lesson: the demo's
    # subject is WHEN money is low, not whether this invented person is
    # solvent. The card carries a real balance, so the emergency fund is lifted
    # to cover it -- which is what an emergency fund is for, and it gives the
    # savings account a float worth talking about on the Savings Pool.
    run = sum(opening.get(a, 0.0) * scale for a in opening)
    low = run
    for r in final:
        run += SIGN[r["type"]] * r["amount"]
        low = min(low, run)
    if low < 0:
        opening["Savings"] = (opening.get("Savings", 0.0) * scale - low + 400.0) / scale

    seed = {
        "meta": {
            "title": "Two months of somebody's money",
            "currency": "GBP",
            "symbol": "£",
            "start": min(r["period"] for r in final),
            "end": max(r["period"] for r in final),
            "generated": dt.date.today().isoformat(),
            "note": (
                "Invented, but with the rhythm of a real ledger: the daily counts, the "
                "share of rows each category takes and the timing of the fixed bills are "
                "kept, while every amount, date and label has been moved or removed. "
                "Currency is one field on the whole file rather than one per row as the "
                "app stores it, because the demo is single-currency and it saves a column "
                "in the ledger below the chart."
            ),
        },
        "accounts": [
            {
                "name": name,
                "opening": round_money(opening.get(name, 0.0) * scale),
                "savings": name in SAVINGS_ACCOUNTS,
            }
            for name in ["Bank Accounts", "Cash", "Wallet", "Credit Card", "Savings"]
        ],
        "sign": SIGN,
        "buckets": {
            "needs": NEEDS,
            "wants": WANTS,
            "targets": {"needs": 0.5, "wants": 0.3, "savings": 0.2},
        },
        "categories": cats,
        "txns": final,
    }

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "seed.json").write_text(json.dumps(seed, indent=1, ensure_ascii=False) + "\n")

    # ------------------------------------------------- report to stdout --
    spend = collections.Counter()
    for r in final:
        if r["type"] == "Expense":
            spend[r["category"]] += r["amount"]
    income = sum(r["amount"] for r in final if r["type"] == "Income")
    print(f"rows      {len(final)}  ({len(window)} in source window)")
    print(f"days      {len(buckets)}")
    print(f"income    {income:,.2f}")
    for c, v in spend.most_common():
        print(f"  {c:<14} {v:9,.2f}")
    print("openings ", {a["name"]: a["opening"] for a in seed["accounts"]})


if __name__ == "__main__":
    main()
